version: "3.5"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    ports:
      - "1234:5432"
  api:
    build: .
    environment:
      - NODE_ENV=development
    command: "npm run dev"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"